# Use Node.js v18 base image
FROM node:18

# Upgrade npm to the latest version (v10)
RUN npm install -g npm@10

# Set the working directory in the container
WORKDIR /app  # This is where your code will reside inside the container

# Copy package.json and package-lock.json files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app will run on
EXPOSE 3001

# Set the command to start the app
CMD ["node", "index.js"]
